# Generated by Django 2.2.28 on 2023-06-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=255)),
                ('company_name', models.CharField(default='RAZÃO SOCIAL...', max_length=255)),
                ('id_establishment', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('ddd', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('cnpj', 'contact_id')},
            },
        ),
        migrations.CreateModel(
            name='Pendencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=255)),
                ('period', models.DateField()),
                ('pdf', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencies', to='contacts.Contact')),
            ],
        ),
    ]
