# Generated by Django 2.2.28 on 2023-06-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companycontact',
            unique_together={('cnpj', 'responsible_name')},
        ),
    ]
