# Generated by Django 4.2.1 on 2023-05-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contact_id', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('period', models.DateField()),
                ('timestamp', models.DateTimeField(default=None)),
                ('status', models.IntegerField(choices=[(0, 'Criada'), (1, 'Enviada'), (2, 'Recebida'), (3, 'Visualizada')])),
                ('ticket_service_id', models.CharField(max_length=255)),
                ('message_type', models.CharField(max_length=255)),
                ('is_from_me', models.BooleanField(default=False)),
                ('text', models.CharField()),
                ('retries', models.IntegerField()),
            ],
            options={
                'unique_together': {('contact_id', 'message_id', 'status')},
            },
        ),
    ]
