# Generated by Django 4.2 on 2023-05-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_cpf', models.CharField(max_length=255)),
                ('period', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Enviada'), (2, 'Recebida'), (3, 'Visualizada')])),
                ('message_id', models.CharField(max_length=255)),
                ('ticket_service_id', models.CharField(max_length=255)),
                ('message_type', models.CharField(max_length=255)),
                ('retries', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('message_id', 'ticket_service_id')},
            },
        ),
    ]
