# Generated by Django 4.2 on 2023-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
