# Generated by Django 4.2 on 2023-05-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
