# Generated by Django 4.2.1 on 2023-05-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
