# Generated by Django 4.2 on 2023-05-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0002_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='period',
            field=models.CharField(),
        ),
    ]
