# Generated by Django 4.2 on 2023-05-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0003_alter_ticket_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_message_id',
            field=models.CharField(default='ndsaujfbnujsafbncuj', max_length=500),
        ),
    ]
