# Generated by Django 4.2 on 2023-05-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messages_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendencies', models.BooleanField()),
                ('contact', models.CharField(max_length=255)),
                ('retries', models.IntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='messages_api.ticket')),
            ],
        ),
    ]
