# Generated by Django 4.2.1 on 2023-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dasfilegrouping",
            name="was_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagecontrol",
            name="check_count",
            field=models.IntegerField(default=0),
        ),
    ]
