# Generated by Django 4.2 on 2023-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontrol',
            name='pendencies',
            field=models.BooleanField(default=False),
        ),
    ]
