# Generated by Django 4.2 on 2023-05-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_messagecontrol_pendencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontrol',
            name='period',
            field=models.DateField(default='2023-05-01'),
        ),
    ]
