# Generated by Django 4.2 on 2023-05-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_messagecontrol_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontrol',
            name='period',
            field=models.DateField(),
        ),
    ]
