# Generated by Django 4.2 on 2023-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_messagecontrol_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontrol',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aguardando Resposta'), (1, 'Fechado')], default=0),
        ),
    ]
