# Generated by Django 4.2 on 2023-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_messagecontrol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontrol',
            name='retries',
            field=models.IntegerField(default=1),
        ),
    ]
