# Generated by Django 4.2 on 2023-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_alter_messagecontrol_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontrol',
            name='client_needs_help',
            field=models.BooleanField(default=False),
        ),
    ]
