# Generated by Django 4.2 on 2023-05-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0004_ticket_last_message_id'),
        ('control', '0008_messagecontrol_client_needs_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_tickets', models.ManyToManyField(blank=True, to='messages_api.ticket')),
                ('message_control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.messagecontrol')),
            ],
        ),
    ]
