# Generated by Django 4.2 on 2023-05-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0004_ticket_last_message_id'),
        ('control', '0009_ticketlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlink',
            name='last_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_ticketlink', to='messages_api.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketlink',
            name='additional_tickets',
            field=models.ManyToManyField(blank=True, related_name='ticketlinks', to='messages_api.ticket'),
        ),
    ]
